name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - name: Setup git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/LineageOS/android_kernel_oneplus_sm8350.git

      - name: Fetch upstream
        run: git fetch upstream

      # Sync lineage branch with the upstream
      - name: Reset lineage branch to match upstream
        run: |
          git checkout -b lineage-23.2 origin/lineage-23.2
          git reset --hard upstream/lineage-23.2

      - name: Push upstream branch
        run: git push origin lineage-23.2 --force

      # Merge working branch with updated upstream branch
      - name: Merge working branch with upstream branch
        id: check_changes
        run: |
          git checkout android-16
          
          # Store the current commit hash
          OLD_HASH=$(git rev-parse HEAD)
          
          # Merge the updated upstream branch
          git merge lineage-23.2
          
          # Store the new commit hash
          NEW_HASH=$(git rev-parse HEAD)
          
          # Compare the hashes to see if anything actually changed
          if [ "$OLD_HASH" != "$NEW_HASH" ]; then
            echo "updated=true" >> $GITHUB_OUTPUT
            echo "Changes detected and merged."
          else
            echo "updated=false" >> $GITHUB_OUTPUT
            echo "No changes detected. Skipping push and build trigger."
          fi

      - name: Push working branch
        if: steps.check_changes.outputs.updated == 'true'
        run: git push origin android-16 --force-with-lease

      - name: Trigger Remote Build Workflow
        if: steps.check_changes.outputs.updated == 'true'
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # Triggers the workflow in the other repository
          gh workflow run build.yml \
            --repo Gamesmes90/build_android_kernel_oneplus_sm8350 \
            --ref android-16